FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies: GCC 11 (supports C++20), Java 17, Python 3.11
RUN apt-get update && apt-get install -y \
    gcc g++ gcc-11 g++-11 \
    python3.11 python3.11-dev python3.11-venv python3-pip \
    python2 python-is-python3 \
    openjdk-17-jdk \
    make cmake git curl \
    libseccomp-dev \
    binutils \
    perl ruby \
    nodejs npm \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 60 \
    && rm -rf /var/lib/apt/lists/*

# Create a virtual environment using Python 3.11 specifically
RUN python3.11 -m venv /judge-env
ENV PATH="/judge-env/bin:$PATH"

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir cython
RUN pip install --no-cache-dir dmoj

# Override the default entrypoint
ENTRYPOINT ["dmoj"]
